name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build . --file Dockerfile --tag porebric/services-metrics:latest
    
      - name: Push
        run: docker push porebric/services-metrics
